jenkins:
  systemMessage: "Pipeline SmartLogi-V2 prêt - Configuration automatique activée"

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

jobs:
  - script: >
      pipelineJob('SmartLogi-V2-Pipeline') {
        description('Pipeline SmartLogi-V2 avec JaCoCo et SonarQube')
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/OumaymaBrd/SmartLogi-V2.git')
                }
                branches('*/master')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }

unclassified:
  sonarGlobalConfiguration:
    installations:
      - name: "SonarQube"
        serverUrl: "http://sonarqube:9000"
        credentialsId: "sonarqube-credentials"
